/**
 * TANTRAMOUR 2026 — Référentiel : Équipements
 * Chaque entrée : { id, value, type, categorie, stock, description, remarque }
 *   value       : nom de l'équipement
 *   type        : "Hameau" | "Tantramour" | "Animateur" | "Autre" (fournisseur)
 *   categorie   : nom de la catégorie — géré via ref_equip_cat.js (REF_EQUIP_CAT)
 *   stock       : nombre (0-1000) ou "N/A"
 *   description : texte libre
 *   remarque    : texte libre
 */
var REF_EQUIPEMENTS = [
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_MAT", value: "Tapis de Yoga", stock: 141, description: "Tapis de Yoga", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_BRIC", value: "Brique de yoga", stock: 34, description: "Brique de yoga", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_MATELAS", value: "Matelas", stock: 169, description: "Matelas", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_MICCASQUE", value: "Micro Casque", stock: "N/A", description: "Micro Casque", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_CHAISE", value: "Chaise", stock: 246, description: "Chaise", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_TABLE", value: "Table", stock: "N/A", description: "Table", remarque: "" },
  { type: "Hameau", categorie: "Fournitures", id: "EQ_BOARD", value: "Paperboard", stock: 12, description: "Paperboard", remarque: "" },
  { type: "Hameau", categorie: "Décoration & Rituel", id: "EQ_MIROIR", value: "Miroir", stock: 1, description: "Miroir", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_SALADIER", value: "Saladier", stock: "N/A", description: "Saladier", remarque: "" },
  { type: "Hameau", categorie: "Consommables Hygiène", id: "EQ_SERVIETTE", value: "Serviette de toilette", stock: "N/A", description: "Serviettes de toilette", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_BASSINE", value: "Bassine", stock: "N/A", description: "Bassine", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_PAN", value: "Casserole", stock: "N/A", description: "Casserole", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_LOUCHE", value: "Louche", stock: "N/A", description: "Louche", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_SPOT", value: "Spot lumineux", stock: "N/A", description: "SPOT (Lumiere)", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_LINGETTE", value: "Lingette humide", stock: "N/A", description: "Lingette humide", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_MOUCHOIR", value: "Boite mouchoirs", stock: "N/A", description: "Boite Mouchoirs", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_TALC", value: "Talc", stock: "N/A", description: "Talc", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_COCO", value: "Huile de coco", stock: "N/A", description: "Huile de coco", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_COUPELLE", value: "Petite coupelle (huile)", stock: "N/A", description: "Petite coupelle", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_CHAUFPLAT", value: "Bougie chauffe plat (vraie)", stock: "N/A", description: "Bougie chauffe plat (vraie", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_BOUGIE", value: "Bougie cierge (vraie)", stock: "N/A", description: "Bougie (vraie)", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_BRIQUET", value: "Briquet", stock: "N/A", description: "Briquet", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_LEDSMALL", value: "Bougie chauffe plat (LED)", stock: "N/A", description: "Bougie LED (petite)", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_LEDBIG", value: "Bougie cierge (LED)", stock: "N/A", description: "Bougie LED (Grande)", remarque: "" },
  { type: "Tantramour", categorie: "Fournitures", id: "EQ_PAPIER", value: "Ramette de papier", stock: "N/A", description: "Paquet de papier", remarque: "" },
  { type: "Tantramour", categorie: "Fournitures", id: "EQ_PEN", value: "Crayon", stock: "N/A", description: "Crayon", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_PALO", value: "Palo Santo", stock: "N/A", description: "Palo Santo", remarque: "" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: "EQ_MASQUE", value: "Masque pour les yeux", stock: "N/A", description: "Masque", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_MICSS", value: "Micro Sans Fil", stock: "N/A", description: "Micro Sans Fil", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_MIC", value: "Micro Câble - Tonor", stock: 1, description: "Micro avec cable", remarque: "" },
  { type: "Animateur", categorie: "Décoration & Rituel", id: "EQ_TENTURE", value: "Tenture", stock: "N/A", description: "Tenture", remarque: "" },
  { type: "Animateur", categorie: "Matériel de Pratique", id: "EQ_TAMBOUR", value: "Tambour", stock: "N/A", description: "Tambour", remarque: "" },
  { type: "Animateur", categorie: "Décoration & Rituel", id: "EQ_CLOCHETTE", value: "Clochette", stock: "N/A", description: "Clochette", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_ROSER", value: "Rose rouge", stock: "N/A", description: "Rose rouge", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_ROSEB", value: "Rose blanche", stock: "N/A", description: "Rose Blanche", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_FLEUR", value: "Bouquet de fleurs (variées)", stock: "N/A", description: "Bouquet de fleurs (variées)", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_ROSES", value: "Bouquet de roses", stock: "N/A", description: "Bouquet de roses", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Technique & Son", id: "EQ_PIEDMIC", value: "Pied Micro", stock: "N/A", description: "Pied Micro + pince micro", remarque: "Demander à Felix" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_NEW01", value: "hfdg", stock: 0, description: "dfhf", remarque: "" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: "EQ_GLACON", value: "Glaçons (Kg)", stock: "N/A", description: "Paquet de glacons", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: "EQ_PISCINE", value: "Piscine gonflable", stock: "N/A", description: "Piscine gonflable", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_MANGEDEB", value: "Table mange debout", stock: 3, description: "Table \"mange debout\"", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_PIEDMICHAM", value: "Pied Micro (Hameau)", stock: 4, description: "Pied Micro (Hameau)", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_RECEPBLUT", value: "Récepteur Bluetooth", stock: 4, description: "Récepteur Bluetooth", remarque: "Récepteur Bluetooth" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_FAUTOSIER", value: "Fauteuil osier", stock: 6, description: "Fauteuil osier", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_FAUTBLAN", value: "Fauteuil blanc", stock: 8, description: "Fauteuil blanc", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_TABGDE2", value: "Grande table pliante #2 (183 cm)", stock: 10, description: "Grande table pliante #2 (183 cm)", remarque: "Grande table pliante grise (183cm/76cm/73cm hauteur)" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_TABPTE", value: "Petite table", stock: 15, description: "Petite Table", remarque: "Petite table noire carrée" },
  { type: "Hameau", categorie: "Décoration & Rituel", id: "EQ_NEW008", value: "Tenture", stock: 16, description: "TISSUS murs - Tentures", remarque: "Tissus murs - Tentures" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_TABMASS", value: "Table de massage", stock: 29, description: "Tables de Massage", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_TABGDE1", value: "Grande table pliante #1 (122 cm)", stock: 58, description: "Grande table pliante #1 (122 cm)", remarque: "Table grise pliante (122cm/60cm/74cm hauteur)" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_TABMIX", value: "Table de mixage", stock: "N/A", description: "Table de mixage", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_SONO", value: "Sono", stock: "N/A", description: "Sono", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_GELHYDRO", value: "Gel hydroalcoolique", stock: "N/A", description: "Gel hydroalcoolique", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_SOPALIN", value: "Sopalin", stock: "N/A", description: "Sopalin", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_ASSGDE", value: "Grande assiette", stock: "N/A", description: "Grande assiette", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_ASSPTE", value: "Petite assiette", stock: "N/A", description: "Petite assiette", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_CUILCAFE", value: "Petite cuillère", stock: "N/A", description: "Petite cuillère", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_CUILSOUP", value: "Cuillère à soupe", stock: "N/A", description: "Cuillère à soupe", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_AUTEL", value: "Sopalin", stock: "N/A", description: "Sopalin", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_ENCENS", value: "Encens", stock: 0, description: "Encens", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_TAPSOL", value: "Tapis de sol décoratif", stock: "N/A", description: "Tapis de sol décoratif", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_CHANDELLE", value: "Bougie chandelle (vraie)", stock: "N/A", description: "Bougie chandelle (vraie)", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_SUPCHAND", value: "Support bougie chandelle", stock: "N/A", description: "Support bougie chandelle", remarque: "" },
  { type: "Tantramour", categorie: "Fournitures", id: "EQ_WATER", value: "Bouteilles d'eau", stock: "N/A", description: "Bouteilles d'eau", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_BOBSEAT", value: "Bobseat", stock: 10, description: "Bobseat", remarque: "" },
  { type: "Animateur", categorie: "Matériel de Pratique", id: "EQ_CORDE", value: "Corde Shibari", stock: "N/A", description: "Corde Shibari", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_COUSSIN", value: "Coussin", stock: 360, description: "Cousin", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_ZAFU", value: "Zafu", stock: 32, description: "Zafu", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW012", value: "Câble Branchement Guitare", stock: "N/A", description: "Câble Branchement Guitare", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW013", value: "Connecteur pour pédalier", stock: "N/A", description: "Connecteur pour pédalier", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW014", value: "Connectique iPhone", stock: "N/A", description: "Connectique iPhone", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_STDGUIT", value: "Stand Guitare", stock: "N/A", description: "Stand Guitare", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW015", value: "Mini-jack pour iMac", stock: "N/A", description: "Mini-jack pour iMac", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW016", value: "Alimentation électrique 220v (3)", stock: "N/A", description: "Alimentation électrique 220v (3)", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW017", value: "Entrée XLR ou Jack 6,35mm", stock: "N/A", description: "Entrée XLR ou Jack 6,35mm", remarque: "" },
  { type: "_", categorie: "_", id: "_", value: "_", stock: "N/A", description: "_", remarque: "_" },
  { type: "Tantramour", categorie: "Cuisine", id: "EQ_GOBELET", value: "Gobelets en carton", stock: 200, description: "Gobelets en carton", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_NEW02", value: "", stock: "N/A", description: "", remarque: "" },
];
