/**
 * TANTRAMOUR 2026 — Référentiel : Équipements
 * Chaque entrée : { id, value, type, categorie, stock, description, remarque }
 *   value       : nom de l'équipement
 *   type        : "Hameau" | "Tantramour" | "Animateur" | "Autre" (fournisseur)
 *   categorie   : nom de la catégorie — géré via ref_equip_cat.js (REF_EQUIP_CAT)
 *   stock       : nombre (0-1000) ou "N/A"
 *   description : texte libre
 *   remarque    : texte libre
 */
var REF_EQUIPEMENTS = [
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_MAT", value: "Tapis de Yoga", stock: 141, description: "Tapis de Yoga", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_BRIC", value: "Brique de yoga", stock: 34, description: "Brique de yoga", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_MATELAS", value: "Matelas", stock: 169, description: "Matelas", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_MICCASQUE", value: "Micro Casque", stock: 0, description: "Micro Casque", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_CHAISE", value: "Chaise", stock: 246, description: "Chaise", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_TABLE", value: "Table", stock: 0, description: "Table", remarque: "" },
  { type: "Hameau", categorie: "Fournitures", id: "EQ_BOARD", value: "Paperboard", stock: 12, description: "Paperboard", remarque: "" },
  { type: "Hameau", categorie: "Décoration & Rituel", id: "EQ_MIROIR", value: "Miroir", stock: 1, description: "Miroir", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_SALADIER", value: "Saladier", stock: 0, description: "Saladier", remarque: "" },
  { type: "Hameau", categorie: "Consommables Hygiène", id: "EQ_SERVIETTE", value: "Serviette de toilette", stock: 0, description: "Serviette de toilette", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_BASSINE", value: "Bassine", stock: 0, description: "Bassine", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_PAN", value: "Casserole", stock: 0, description: "Casserole", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_LOUCHE", value: "Louche", stock: 0, description: "Louche", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_SPOT", value: "Spot lumineux", stock: 0, description: "Spot lumineux", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_LINGETTE", value: "Lingette humide", stock: 0, description: "Lingette humide", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_MOUCHOIR", value: "Boite mouchoirs", stock: 0, description: "Boite mouchoirs", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_TALC", value: "Talc", stock: 0, description: "Talc", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_COCO", value: "Huile de coco", stock: 0, description: "Huile de coco", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_COUPELLE", value: "Petite coupelle (huile)", stock: 0, description: "Petite coupelle (huile)", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_CHAUFPLAT", value: "Bougie chauffe plat (vraie)", stock: 0, description: "Bougie chauffe plat (vraie)", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_BOUGIE", value: "Bougie cierge (vraie)", stock: 0, description: "Bougie cierge (vraie)", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_BRIQUET", value: "Briquet", stock: 0, description: "Briquet", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_LEDSMALL", value: "Bougie chauffe plat (LED)", stock: 0, description: "Bougie chauffe plat (LED)", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_LEDBIG", value: "Bougie cierge (LED)", stock: 0, description: "Bougie cierge (LED)", remarque: "" },
  { type: "Tantramour", categorie: "Fournitures", id: "EQ_PAPIER", value: "Ramette de papier", stock: 0, description: "Ramette de papier", remarque: "" },
  { type: "Tantramour", categorie: "Fournitures", id: "EQ_PEN", value: "Crayon", stock: 0, description: "Crayon", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_PALO", value: "Palo Santo", stock: 0, description: "Palo Santo", remarque: "" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: "EQ_MASQUE", value: "Masque pour les yeux", stock: 0, description: "Masque pour les yeux", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_MICSS", value: "Micro Sans Fil", stock: 0, description: "Micro Sans Fil", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_MIC", value: "Micro Câble - Tonor", stock: 1, description: "Micro Câble - Tonor", remarque: "" },
  { type: "Animateur", categorie: "Décoration & Rituel", id: "EQ_TENTURE", value: "Tenture", stock: 0, description: "Tenture", remarque: "" },
  { type: "Animateur", categorie: "Matériel de Pratique", id: "EQ_TAMBOUR", value: "Tambour", stock: 0, description: "Tambour", remarque: "" },
  { type: "Animateur", categorie: "Décoration & Rituel", id: "EQ_CLOCHETTE", value: "Clochette", stock: 0, description: "Clochette", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_ROSER", value: "Rose rouge", stock: 0, description: "Rose rouge", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_ROSEB", value: "Rose blanche", stock: 0, description: "Rose blanche", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_FLEUR", value: "Bouquet de fleurs (variées)", stock: 0, description: "Bouquet de fleurs (variées)", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_ROSES", value: "Bouquet de roses", stock: 0, description: "Bouquet de roses", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Technique & Son", id: "EQ_PIEDMIC", value: "Pied Micro (FELIX)", stock: 0, description: "Pied Micro (FELIX)", remarque: "Demander à Felix" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_NEW01", value: "Connecteur iPhone 16", stock: "N/A", description: "Connecteur iPhone 16", remarque: "pour playlist" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: "EQ_GLACON", value: "Glaçons (Kg)", stock: 0, description: "Glaçons (Kg)", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: "EQ_PISCINE", value: "Piscine gonflable", stock: 0, description: "Piscine gonflable", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_NEW000", value: "Table mange debout", stock: 3, description: "Table mange debout", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_NEW001", value: "Pied Micro (Hameau)", stock: 4, description: "Pied Micro (Hameau)", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_NEW002", value: "Récepteur Bluetooth", stock: 4, description: "Récepteur Bluetooth", remarque: "Récepteur Bluetooth" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_NEW003", value: "Fauteuil osier", stock: 6, description: "Fauteuil osier", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_NEW004", value: "Fauteuil blanc", stock: 8, description: "Fauteuil blanc", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_NEW005", value: "Bobseat", stock: 10, description: "Bobseat", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_NEW006", value: "Grande table pliante #2 (183 cm)", stock: 10, description: "Grande table pliante #2 (183 cm)", remarque: "Grande table pliante grise (183cm/76cm/73cm hauteur)" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_NEW007", value: "Petite table", stock: 15, description: "Petite table", remarque: "Petite table noire carrée" },
  { type: "Hameau", categorie: "Décoration & Rituel", id: "EQ_NEW008", value: "Tenture", stock: 16, description: "Tenture", remarque: "Tissus murs - Tentures" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_NEW009", value: "Table de massage", stock: 29, description: "Table de massage", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_NEW010", value: "Zafu festivalier", stock: 32, description: "Zafu festivalier", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: "EQ_NEW011", value: "Grande table pliante #1 (122 cm)", stock: 58, description: "Grande table pliante #1 (122 cm)", remarque: "Table grise pliante (122cm/60cm/74cm hauteur)" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_NEW02", value: "Encens", stock: 0, description: "Encens", remarque: "" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: "EQ_NEW03", value: "Masque", stock: "N/A", description: "Masque", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_TABMIX", value: "Table de mixage", stock: 0, description: "Table de mixage", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: "EQ_SONO", value: "Sono", stock: 0, description: "Sono", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_ASSGDE", value: "Assiette grande", stock: 0, description: "Assiette grande", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_ASSPTE", value: "Assiette petite", stock: 0, description: "Assiette petite", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_AUTEL", value: "Sopalin", stock: 0, description: "Sopalin", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_BOBSEAT", value: "Bobseat", stock: 10, description: "Bobseat", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_CHANDELLE", value: "Bougie chandelle (vraie)", stock: 0, description: "Bougie chandelle (vraie)", remarque: "" },
  { type: "Animateur", categorie: "Matériel de Pratique", id: "EQ_CORDE", value: "Corde Shibari", stock: 0, description: "Corde Shibari", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_COUSSIN", value: "Coussin", stock: 360, description: "Coussin", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_CUILCF", value: "Cuillère à café", stock: 0, description: "Cuillère à café", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: "EQ_CUILSP", value: "Cuillière à soupe", stock: 0, description: "Cuillière à soupe", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_ENCENS", value: "Encens", stock: 0, description: "Encens", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_GELHYDRO", value: "Gel hydroalcoolique", stock: 0, description: "Gel hydroalcoolique", remarque: "" },
  { type: "Tantramour", categorie: "Cuisine", id: "EQ_GOBELET", value: "Gobelet carton", stock: 200, description: "Gobelet carton", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW012", value: "Câble Branchement Guitare", stock: 0, description: "Câble Branchement Guitare", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW013", value: "Connecteur pour pédalier", stock: 0, description: "Connecteur pour pédalier", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW014", value: "Connectique iPhone", stock: 0, description: "Connectique iPhone", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW015", value: "Mini-jack pour iMac", stock: 0, description: "Mini-jack pour iMac", remarque: "" },
  { type: "Autre", categorie: "Technique & Son", id: "EQ_NEW016", value: "Alimentation électrique 220v (3)", stock: "N/A", description: "Alimentation électrique 220v (3)", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_NEW017", value: "Entrée XLR ou Jack 6,35mm", stock: 0, description: "Entrée XLR ou Jack 6,35mm", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_SESAME", value: "Huile de sésame", stock: 0, description: "Huile de sésame", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: "EQ_SOPALIN", value: "Sopalin", stock: 0, description: "Sopalin", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: "EQ_STDGUIT", value: "Stand Guitare", stock: 0, description: "Stand Guitare", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: "EQ_SUPCHAND", value: "Support bougie chandelle", stock: 0, description: "Support bougie chandelle", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_TAPSOL", value: "Tapis de sol décoratif", stock: 0, description: "Tapis de sol décoratif", remarque: "" },
  { type: "Tantramour", categorie: "Fournitures", id: "EQ_WATER", value: "Bouteilles d'eau", stock: 0, description: "Bouteilles d'eau", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: "EQ_ZAFU", value: "Zafu animateur", stock: 32, description: "Zafu animateur", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: "EQ_NEW04", value: "Petites fleurs séchées", stock: 0, description: "pour autel Shiva", remarque: "" }
];
